stages:
  - build
  - update

variables:
  AWS_REGION: "us-west-2"
  ECR_REPO_URL: "381492168839.dkr.ecr.us-west-2.amazonaws.com/stage-explorer-sync-aleph-foresight"
  REPO_URL: "git@repo.antiersolutions.com:jogesh/aleph-foresight-k8-deployments.git"
  TARGET_BRANCH: "stage"

build:
  stage: build
  image: python:3.10-slim
  services:
    - docker:19.03.12-dind
  before_script:
    - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPO_URL
    - docker --version
    - docker info
  script:
    - echo "Building Docker image..."
    - docker build -t $ECR_REPO_URL:$CI_COMMIT_SHORT_SHA .
    - docker push $ECR_REPO_URL:$CI_COMMIT_SHORT_SHA
  only:
    - feature/pipeline

update_deployment:
  stage: update
  image: python:3.10-slim
  variables:
    GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
  before_script:
    - apt-get update && apt-get install -y git openssh-client
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
  script:
    - echo "Cloning deployment repository..."
    - git clone -b $TARGET_BRANCH $REPO_URL
    - cd aleph-foresight-k8-deployments/explorer/sync
    - echo "Updating deployment.yaml with new image tag..."
    - yq eval ".spec.template.spec.containers[0].image = \"${ECR_REPO_URL}:${CI_COMMIT_SHORT_SHA}\"" -i deployment.yaml
    - git config --global user.email "your-email@example.com"
    - git config --global user.name "Your Name"
    - git add deployment.yaml
    - git commit -m "Updated image tag to ${CI_COMMIT_SHORT_SHA}"
    - git push origin $TARGET_BRANCH
  only:
    - feature/pipeline

