image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  AWS_DEFAULT_REGION: us-west-2
  ECR_REGISTRY: 381492168839.dkr.ecr.us-west-2.amazonaws.com
  ECR_REPOSITORY: stage-explorer-sync-aleph-foresight
  IMAGE_TAG: $CI_COMMIT_SHA

before_script:
  - apt-get update
  - apt-get install -y python3-pip
  - pip3 install awscli
  - $(aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY)
  - echo "Logged into ECR"

stages:
  - build
  - push

build_image:
  stage: build
  script:
    - docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
  only:
    - feature/pipeline

push_image:
  stage: push
  script:
    - docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
  only:
    - feature/pipeline
