stages:
  - build
  - clone
  - update

variables:
  AWS_REGION: "us-west-2"
  ECR_REPO_URL: "381492168839.dkr.ecr.us-west-2.amazonaws.com/stage-explorer-sync-aleph-foresight"
  REPO_URL: "git@repo.antiersolutions.com:jogesh/aleph-foresight-k8-deployments.git"
  TARGET_BRANCH: "stage"
  REGISTRY: "381492168839.dkr.ecr.us-west-2.amazonaws.com"
  ECR_REPOSITORY: "stage-explorer-sync-aleph-foresight"

build:
  stage: build
  image: python:3.10-slim
  services:
    - docker:19.03.12-dind
  before_script:
    - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPO_URL
    - docker --version
    - docker info
  script:
    - echo "Building Docker image..."
    - docker build -t $ECR_REPO_URL:$CI_COMMIT_SHORT_SHA .
    - docker push $ECR_REPO_URL:$CI_COMMIT_SHORT_SHA
  only:
    - feature/pipeline

clone_project:
  stage: clone
  image: python:3.10-slim
  before_script:
    - apt-get update && apt-get install -y git openssh-client curl
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H repo.antiersolutions.com >> ~/.ssh/known_hosts
  script:
    - echo "Cloning deployment repository..."
    - git clone -b $TARGET_BRANCH $REPO_URL
    - cd aleph-foresight-k8-deployments/explorer/sync
    - echo "Updating deployment.yaml with new image tag"
    - sed -i "s|image:.*|image: ${REGISTRY}/${ECR_REPOSITORY}:${CI_COMMIT_SHORT_SHA}|" deployment.yaml
  only:
    - feature/pipeline
