stages:
  - build

variables:
  AWS_REGION: "us-west-2"
  ECR_REPO_URL: "381492168839.dkr.ecr.us-west-2.amazonaws.com/stage-explorer-sync-aleph-foresight"

build:
  stage: build
  image: docker:19.03.12
  services:
    - docker:19.03.12-dind
  before_script:
    - apt add --no-cache bash git openssh python3 py3-pip
    - pip3 install awscli
    - aws --version
    - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPO_URL
    - docker --version
    - docker info
  script:
    - echo "Building Docker image..."
    - docker build -t $ECR_REPO_URL:$CI_COMMIT_SHORT_SHA .
    - docker push $ECR_REPO_URL:$CI_COMMIT_SHORT_SHA
  only:
    - feature/pipeline
